### ISSUE TITLE
Problems running Bulk Validation

### ISSUE THREAD

**Issue by MichaelOstling** [INSPIRE-MIF/helpdesk-validator#371]
I'm trying to set up the validator as described here
https://github.com/inspire-eu-validation/monitoring-bulk-validation-tool

When starting the validator.bat it runs for 30 s then I get the following in pdi.log

```
2020-08-12 11:02:02.914 INFO  <init of validate multi-node.0 (Thread-66)> [F:\Dropbox\metagis\dev\InspireBulkValidation\pdi\validation.kjb  file:///F:/Dropbox/metagis/dev/InspireBulkValidation/pdi/validate_endpoint.ktr  file:///F:/Dropbox/metagis/dev/InspireBulkValidation/pdi/validate_cycle_sub.ktr]  Dispatching started for transformation [validate cycle]
2020-08-12 11:02:02.929 INFO  <init of read endpoint.0 (Thread-61)> [F:\Dropbox\metagis\dev\InspireBulkValidation\pdi\validation.kjb  file:///F:/Dropbox/metagis/dev/InspireBulkValidation/pdi/validate_endpoint.ktr  file:///F:/Dropbox/metagis/dev/InspireBulkValidation/pdi/read_endpoint.ktr]  Dispatching started for transformation [read endpoint]
2020-08-12 11:02:03.194 ERROR <init of validate multi-node.0 (Thread-66)> [F:\Dropbox\metagis\dev\InspireBulkValidation\pdi\validation.kjb  file:///F:/Dropbox/metagis/dev/InspireBulkValidation/pdi/validate_endpoint.ktr  file:///F:/Dropbox/metagis/dev/InspireBulkValidation/pdi/validate_cycle_sub.ktr]  Error initializing UserDefinedJavaClass:
2020-08-12 11:02:03.197 ERROR <init of validate multi-node.0 (Thread-66)> [F:\Dropbox\metagis\dev\InspireBulkValidation\pdi\validation.kjb  file:///F:/Dropbox/metagis/dev/InspireBulkValidation/pdi/validate_endpoint.ktr  file:///F:/Dropbox/metagis/dev/InspireBulkValidation/pdi/validate_cycle_sub.ktr]  org.codehaus.commons.compiler.CompileException: Line 1, Column 7: A class "inspire.validator.Queue" could not be found

2020-08-12 11:02:03.199 ERROR <init of validate multi-node.0 (Thread-66)> [F:\Dropbox\metagis\dev\InspireBulkValidation\pdi\validation.kjb  file:///F:/Dropbox/metagis/dev/InspireBulkValidation/pdi/validate_endpoint.ktr  file:///F:/Dropbox/metagis/dev/InspireBulkValidation/pdi/validate_cycle_sub.ktr]  Something went wrong while trying to safe stop the transformation: 
2020-08-12 11:02:03.202 ERROR <init of validate multi-node.0 (Thread-66)> [F:\Dropbox\metagis\dev\InspireBulkValidation\pdi\validation.kjb  file:///F:/Dropbox/metagis/dev/InspireBulkValidation/pdi/validate_endpoint.ktr  file:///F:/Dropbox/metagis/dev/InspireBulkValidation/pdi/validate_cycle_sub.ktr]  java.lang.NullPointerException
	at org.pentaho.di.trans.steps.simplemapping.SimpleMapping.stopRunning(SimpleMapping.java:293)
	at org.pentaho.di.trans.Trans.stopStep(Trans.java:2044)
	at org.pentaho.di.trans.Trans.lambda$stopAll$2(Trans.java:2028)
	at java.util.ArrayList.forEach(Unknown Source)
	at org.pentaho.di.trans.Trans.stopAll(Trans.java:2028)
	at org.pentaho.di.trans.step.BaseStep.stopAll(BaseStep.java:3008)
	at org.pentaho.di.trans.steps.userdefinedjavaclass.UserDefinedJavaClass.stopAllImpl(UserDefinedJavaClass.java:1286)
	at org.pentaho.di.trans.steps.userdefinedjavaclass.UserDefinedJavaClass.<init>(UserDefinedJavaClass.java:70)
	at org.pentaho.di.trans.steps.userdefinedjavaclass.UserDefinedJavaClassMeta.getStep(UserDefinedJavaClassMeta.java:717)
	at org.pentaho.di.trans.Trans.prepareExecution(Trans.java:1041)
	at org.pentaho.di.trans.steps.simplemapping.SimpleMapping.prepareMappingExecution(SimpleMapping.java:177)
	at org.pentaho.di.trans.steps.simplemapping.SimpleMapping.init(SimpleMapping.java:255)
	at org.pentaho.di.trans.step.StepInitThread.run(StepInitThread.java:69)
	at java.lang.Thread.run(Unknown Source)
```
Im running on a windows 10 machine usingJava 1.8
the path in validation.bat is set as  
`F:\dropbox\metagis\dev\InspireBulkValidation\pdi\data-integration\Kitchen.bat /file:pdi\validation.kjb "/param:config=config.properties"
`

in config.properties I have set as below

```
endpoint=GSEMetadata
source_folder=F:/dropbox/metagis/dev/InspireBulkValidation/export-full-1597219127626/metadata
results_folder=F:/dropbox/metagis/dev/InspireBulkValidation/GSEResult
source_suffix=.xml
validator_nodes=1
validator_url_0=http://etf.geodatavalidering.se/etf-webapp
```

Im not sure if you can help me out with these short desciptions
Im also attaching the the full logg-files.

/Michael Östling

[pdi.log](https://github.com/inspire-eu-validation/community/files/5061726/pdi.log)
[karaf.log](https://github.com/inspire-eu-validation/community/files/5061728/karaf.log)

**Comment by ukiz** [comment]
Dear Michael,

the problem seems to be 'A class "inspire.validator.Queue" could not be found'.
Please make sure to copy the _inspire-validator.jar_ to your PDI lib folder (i.e. _F:\dropbox\metagis\dev\InspireBulkValidation\pdi\data-integration\lib_)

Also, in your _config.properties_ please change the validator url:
`validator_url_0=http://etf.geodatavalidering.se/etf-webapp/v2/`

Kind regards,

Lukasz Ziemba

**Comment by MichaelOstling** [comment]
Thanks for quick reply.
It was the **inspire-validator.jar** that was corrupted during my download.
I replaced it and now the process runs.
