### ISSUE TITLE
crash when the queue is too busy

### ISSUE THREAD

**Issue by axel584** [INSPIRE-MIF/helpdesk-validator#463]
Hello,
We have installed an instance of Validator 2020.1.2 on our own infrastructure and we see frequent errors when the server is used by several clients simultaneously:
```
2020-12-02 12:50:31.652 [qtp1973538135-14] ERROR d.i.e.w.d.ApiError - EXID-1606913431652: An exception occurred while trying to invoke "http://localhost:8080/validator/v2/TestRuns"
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is de.interactive_instruments.etf.webapp.controller.LocalizableApiError: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@74e9649e rejected from java.util.concurrent.ThreadPoolExecutor@15f53fa6[Running, pool size = 2, active threads = 2, queued tasks = 6, completed tasks = 10038]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:982)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
	at de.interactive_instruments.etf.webapp.filter.ApiFilter.doFilterInternal(ApiFilter.java:89)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: de.interactive_instruments.etf.webapp.controller.LocalizableApiError: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@74e9649e rejected from java.util.concurrent.ThreadPoolExecutor@15f53fa6[Running, pool size = 2, active threads = 2, queued tasks = 6, completed tasks = 10038]
	at de.interactive_instruments.etf.webapp.controller.TestRunController.initAndSubmit(TestRunController.java:260)
	at de.interactive_instruments.etf.webapp.controller.TestRunController.start(TestRunController.java:510)
	at sun.reflect.GeneratedMethodAccessor207.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	... 36 common frames omitted
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@74e9649e rejected from java.util.concurrent.ThreadPoolExecutor@15f53fa6[Running, pool size = 2, active threads = 2, queued tasks = 6, completed tasks = 10038]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
	at de.interactive_instruments.etf.testdriver.TaskPoolRegistry.submitTask(TaskPoolRegistry.java:162)
	at de.interactive_instruments.etf.webapp.controller.TestRunController.initAndSubmit(TestRunController.java:258)
	... 47 common frames omitted
```
	

For the moment we have left the default configuration and we have 2 CPUs (so a maximum queue with a value of 6)

What do you advise me to avoid having this problem again?

Thanks for your help,

Axel Rousseau
BRGM - France

**Comment by carlospzurita** [comment]
Dear @axel584 

This exception is due to the maximum size of the queue. All Test Runs that cannot be attended right away are sent to the queue. As you pointed out, this value is set by default to three times the number of concurrent tests, and this is set by default to the number of CPU cores.

This error is just the system rejecting a new Test Run once the queue is full, but is not a crash on the validator. After clearing up the queue, the service can receive new Test Runs. You can delay this issue by modifying the value of the property `etf.testruns.queued.max` to a higher value, but mind you, those Test Runs in the queue are occupying memory and need to be attended by the server, and may cause an overload of the system.

One way to avoid the crash is to keep checking the API call `/v2/TestRuns?view=progress`, to see how many Tests are running before sending a new Test Run.

**Comment by carlospzurita** [comment]
Dear  @axel584 

Did you have any success applying the recommendations from the latest comment?

**Comment by fabiovinci** [comment]
Dear @axel584,

do you still have the problem? Have you tried the latest version?

**Comment by fabiovinci** [comment]
Dear @axel584 
since there was no reply, I will close the issue.
Please reopen it or open a new issue if the error persists.
