### ISSUE TITLE
Is Java 11 working ?

### ISSUE THREAD

**Issue by axel584** [INSPIRE-MIF/helpdesk-validator#503]
Hi,
I try to launch the validator with a JDK 11 and I've got the error : 

Did someone success to use java 11 to launch the validator ?

```
27-Jan-2021 10:43:18.702 WARNING [http-nio-8080-exec-2] org.springframework.web.context.support.XmlWebApplicationContext.refresh Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataStorageService': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/Unmarshaller$Listener
27-Jan-2021 10:43:18.704 SEVERE [http-nio-8080-exec-2] org.springframework.web.context.ContextLoader.initWebApplicationContext Context initialization failed
	org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataStorageService': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/Unmarshaller$Listener
		at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:137)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
		at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
```

**Comment by carlospzurita** [comment]
Dear @axel584 

The INSPIRE validator currently don't have support of Java 11. It is developed using Java 8 and right now is not planned to move forward with the migration to a newer version.

You can request this modification on the ETF, the backend framework for the validator, on https://github.com/etf-validator/etf-webapp

Kind regards.

**Comment by dperezBM** [comment]
Dear @axel584

We proceed to close this issue. Do not hesitate to reopen the issue if you have more questions.

Best regards.

**Comment by Dnoack49** [comment]
Dear @dperezBM ,
we currently use a local instance of the validator (but no Docker-image) and our machines will switch to java 11 within a couple months. A year after this question of Java 11 was raised, we would like to know if there are any plans to move it to the new java-version?
Kind regards,
