### ISSUE TITLE
WFS validation failure - groovy script compilation error

### ISSUE THREAD

**Issue by danieluct** [INSPIRE-MIF/helpdesk-validator#576]
Hi,
We are trying to re-validate a WFS service that was working last year:
[https://inspire.meteoromania.ro/WIGOS/WFS?service=WFS&request=GetCapabilities](url)

Beside the known open issue related to Spatial Join (see #209 ) we encountered an unexpected error in the Direct WFS and Pre-defined WFS Validation:
![image](https://user-images.githubusercontent.com/6768817/124104896-62ddf000-da6b-11eb-86eb-8a0ca24472ad.png)

The following extended error is reported by the validator:
```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
Script1.groovy: 16: expecting '}', found 'if' @ line 16, column 67.
   .getTestStepByName(operation) if(testSte
                                 ^
org.codehaus.groovy.syntax.SyntaxException: expecting '}', found 'if' @ line 16, column 67.
	at org.codehaus.groovy.antlr.AntlrParserPlugin.transformCSTIntoAST(AntlrParserPlugin.java:140)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.parseCST(AntlrParserPlugin.java:108)
	at org.codehaus.groovy.control.SourceUnit.parse(SourceUnit.java:236)
	at org.codehaus.groovy.control.CompilationUnit$1.call(CompilationUnit.java:162)
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:912)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:574)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:550)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:527)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:279)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:258)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:613)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:625)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:652)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:643)
	at com.eviware.soapui.support.scripting.groovy.SoapUIGroovyScriptEngine.compile(SoapUIGroovyScriptEngine.java:138)
	at com.eviware.soapui.support.scripting.groovy.SoapUIGroovyScriptEngine.run(SoapUIGroovyScriptEngine.java:89)
	at com.eviware.soapui.impl.wsdl.teststeps.WsdlGroovyScriptTestStep.run(WsdlGroovyScriptTestStep.java:141)
	at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.runTestStep(AbstractTestCaseRunner.java:211)
	at com.eviware.soapui.impl.wsdl.testcase.WsdlTestCaseRunner.runCurrentTestStep(WsdlTestCaseRunner.java:47)
	at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.internalRun(AbstractTestCaseRunner.java:138)
	at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.internalRun(AbstractTestCaseRunner.java:46)
	at com.eviware.soapui.impl.wsdl.support.AbstractTestRunner.run(AbstractTestRunner.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: Script1.groovy:16:67: expecting '}', found 'if'
	at groovyjarjarantlr.Parser.match(Parser.java:211)
	at org.codehaus.groovy.antlr.parser.GroovyRecognizer.openBlock(GroovyRecognizer.java:8317)
	at org.codehaus.groovy.antlr.parser.GroovyRecognizer.compoundStatement(GroovyRecognizer.java:7518)
	at org.codehaus.groovy.antlr.parser.GroovyRecognizer.compatibleBodyStatement(GroovyRecognizer.java:8963)
	at org.codehaus.groovy.antlr.parser.GroovyRecognizer.statement(GroovyRecognizer.java:899)
	at org.codehaus.groovy.antlr.parser.GroovyRecognizer.blockBody(GroovyRecognizer.java:1581)
	at org.codehaus.groovy.antlr.parser.GroovyRecognizer.openBlock(GroovyRecognizer.java:8315)
	at org.codehaus.groovy.antlr.parser.GroovyRecognizer.compoundStatement(GroovyRecognizer.java:7518)
	at org.codehaus.groovy.antlr.parser.GroovyRecognizer.compatibleBodyStatement(GroovyRecognizer.java:8963)
	at org.codehaus.groovy.antlr.parser.GroovyRecognizer.forStatement(GroovyRecognizer.java:9165)
	at org.codehaus.groovy.antlr.parser.GroovyRecognizer.statement(GroovyRecognizer.java:980)
	at org.codehaus.groovy.antlr.parser.GroovyRecognizer.compilationUnit(GroovyRecognizer.java:757)
	at org.codehaus.groovy.antlr.AntlrParserPlugin.transformCSTIntoAST(AntlrParserPlugin.java:131)
	... 26 more

1 error 
```

We think the issue is the lack of a semicolon at the end of this line:
https://github.com/inspire-eu-validation/ets-repository/blob/3ed17ef069b758420063fadb9c6872e4ff26dfa9/service/ds-wfs-direct-soapui-project.xml#L234

**Comment by igea-jure** [comment]
Same thing also in https://github.com/inspire-eu-validation/ets-repository/blob/v2021.2/service/ds-wfs-pre-defined-soapui-project.xml#L2739

**Comment by igea-jure** [comment]
Also here:
- https://github.com/inspire-eu-validation/ets-repository/blob/v2021.2/service/ds-wfs-pre-defined-soapui-project.xml#L3156
- https://github.com/inspire-eu-validation/ets-repository/blob/v2021.2/service/ds-wfs-pre-defined-soapui-project.xml#L3284

**Comment by dperezBM** [comment]
Dear @danieluct and @igea-jure,

We deployed a correction on our [staging instance](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/home/index.html). Could you please check if this is valid for you?

Thank you and best regards.
David.

**Comment by danieluct** [comment]
@dperezBM 
It appears to be working correctly in staging.
Regards

**Comment by fabiovin** [comment]
Dear @danieluct,

thank you for the test.
We will include the fix in the next release.

**Comment by danieluct** [comment]
@fabiovin Thank you and your team for the fix.
