### ISSUE TITLE
Problem with the test case "OpenSearch Description Query examples for each dataset" of predefined-ATOM

### ISSUE THREAD

**Issue by JackyDFu** [INSPIRE-MIF/helpdesk-validator#642]
Regarding the test step "Iterate over Describe Spatial Dataset URL", after changing the `Level of Detail`
in the Report by clicking on `All Details`, I wanted to ask, the test code in the test report is described as:
```
import de.interactive_instruments.xtf.*;
...
def describeSpatialDataSetUrlTemplates = xmlHolder.getDomNodes(
	"/*:OpenSearchDescription/*:Url[@rel='results' and starts-with(@template,'http') and "+
	"contains(@template,'crs') and contains(@template,'spatial_dataset_identifier_code') and "+
	"contains(@template,'spatial_dataset_identifier_namespace') and contains(@template,'language')]");
log.info("describeSpatialDataSetUrls: " + describeSpatialDataSetUrlTemplates);
```

This seems wrong. Shouldn't it be rather using the url with the relation-attribute "describeby" for executing the aboved mentioned the test case "Iterate over Describe Spatial Dataset URL", maybe like so:
```
...
def describeSpatialDataSetUrlTemplates = xmlHolder.getDomNodes(
	"/*:OpenSearchDescription/*:Url[@rel='describedby' and starts-with(@template,'http') and contains(@template,'spatial_dataset_identifier_code') and "+
	"contains(@template,'spatial_dataset_identifier_namespace') and contains(@template,'language')]");
log.info("describeSpatialDataSetUrls: " + describeSpatialDataSetUrlTemplates);
```

EDIT: add screenshot in the test report with the test code:
![grafik](https://user-images.githubusercontent.com/29784918/139217802-ef0ddd7a-0020-43e5-bb6c-dec87c46434c.png)

We discovered this after testing our predefined ATOM, which is accessible using the url
https://www.srp-gmbh.de/fb/feed/senstadt/a_AD_AdressenBerlin

Test was executed as the following:

1. Call https://inspire.ec.europa.eu/validator/test-selection/index.html
2. Select "Download Service"
3. Select pre-defined ATOM
4. Submit service url https://www.srp-gmbh.de/fb/feed/senstadt/a_AD_AdressenBerlin
5. Execute test

**Comment by dperezBM** [comment]
Dear @JackyDFu,

Thank you for addressing this issue. We will analyze your proposal and we will come back to you once a decision is made.

Best regards.

**Comment by JackyDFu** [comment]
Dear @dperezBM,

thank you very much for your support. We tried the test again using the staging platform, the test-report-URL:

http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/details.html?id=EID8ac7f59f-791d-4fa6-ab65-4e744e5fe287

But we encountered the same issue, there are two messages attached to the test "Iterate over Describe Spatial Dataset URL". 
Message 1 states:
`java.lang.IllegalStateException: java.lang.ArrayIndexOutOfBoundsException: -1`
Link: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/validator//v2/TestTaskResults/EIDbdf276be-e3d0-4863-8b2a-79b360966e59/Attachments/EIDe896cf5a-fbc1-49ce-a0ed-26829aea5b60

and message 2:
`error at line: 74`
corresponding link: http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/validator//v2/TestTaskResults/EIDbdf276be-e3d0-4863-8b2a-79b360966e59/Attachments/EIDab4c581b-e807-4b02-af62-332bdc2f32e6

Do these error messages indicate the issue's cause? Based on these messages. we unfortunately could not resolve the problem's source.

We have an assumption though (you surely know better :)), as it seems there is still an issue with the "describe spatial dataset"-link retrieval part:

`def describeSpatialDataSetUrlTemplates = xmlHolder.getDomNodes(
	"/*:OpenSearchDescription/*:Url[@rel='describedby' and starts-with(@template,'http') and "+
	"contains(@template,'crs') and contains(@template,'spatial_dataset_identifier_code') and "+
	"contains(@template,'spatial_dataset_identifier_namespace') and contains(@template,'language')]");
log.info("describeSpatialDataSetUrls: " + describeSpatialDataSetUrlTemplates);`

Our feed service does contain a crs-template parameter, but if I see it correctly the test code does not replace the latter:

EDIT: fix markup
```
for( node in describeSpatialDataSetUrlTemplates ) {
	String describeSpatialDataSetUrlTemplate = node.attributes.getNamedItem("template").getNodeValue()
	String mimeType = node.attributes.getNamedItem("type").getNodeValue()

	log.info("Using template URL: "+describeSpatialDataSetUrlTemplate);
	def parameters = UriUtils.getQueryParameters(describeSpatialDataSetUrlTemplate, false)
	final Map<String, String> cleanParameters = initDefaultParameters(parameters)
	final String endpoint = UriUtils.withoutQueryParameters(describeSpatialDataSetUrlTemplate)

	for(int j=0; j<codes.size(); j++) {
		replaceParameter(parameters, cleanParameters, "inspire_dls:spatial_dataset_identifier_code", codes[j] )
		replaceParameter(parameters, cleanParameters, "inspire_dls:spatial_dataset_identifier_namespace", namespaces[j] )

			for(language in languages) {
				replaceParameter(parameters, cleanParameters, "language", language )
				final String url = UriUtils.withQueryParameters(endpoint, cleanParameters)
				if(!invokedUrls.contains(url)) {
					log.info("Using URL: "+url)
					ph.setTransferProperty("describeSpatialDataSetUrl", url)
					ph.setTransferProperty("mimeType", mimeType)
					ph.runTestStep("Describe Spatial Dataset");
					ph.runTestStep("Iterate over Get Spatial Dataset URL");
					invokedUrls.add(url);
				}
			}
	}
}
```

So considering the assumption is correct, there are basically two options:

1. Remove the crs template parameter from "describe spatial dataset"-url retrieval and our feed service implementation
2. Or add "replace crs parameter" in the test code


Furthermore one can see in the test two testSteps are executed, namely:

- Describe Spatial Dataset
- Iterate Over Get Spatial Dataset URL

I would not expect the second test step to iterate over get spatial dataset url, is this intentional?

**Comment by milanSch** [comment]
Dear @dperezBM, @JackyDFu 

please, I would like to ask you about this issue progress. 

During the last days I tried validated my Atom Download Service a lot of times.

The last test report is here:
https://inspire.ec.europa.eu/validator/test-run/details.html?id=EIDb05e6249-ec3d-4d11-8d8a-4f696a61ec9f

https://yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator/v2/TestRuns/EIDb05e6249-ec3d-4d11-8d8a-4f696a61ec9f.html?lang=en#EID60b2691e-017f-1000-bd3c-aae3a08dfbbc

I have the same problem as  @JackyDFu. 

![image](https://user-images.githubusercontent.com/4444428/156939663-64b6aa4b-c671-4f83-9166-b60be8ffc6a2.png)

Error messages:
- java.lang.IllegalStateException: java.lang.ArrayIndexOutOfBoundsException: -1
- error at line: 74



I can see that a code used in "Iterate over Describe Spatial Dataset Url" appears in INSPIRE validator report twice:

- /Conformance Class: Download Service - Pre-defined Atom / OpenSearch Description / Describe Spatial Dataset Operation / Iterate over Describe Spatial Dataset Url
- /Conformance Class: Download Service - Pre-defined Atom / OpenSearch Description / Query examples for each dataset / Iterate over Describe Spatial Dataset Url

First occurrence seems to be OK.
![image](https://user-images.githubusercontent.com/4444428/156940351-3dcfec60-f40b-4b33-92f9-202f11e2dbc0.png)

Second occurrence seems to be wrong, not corrected?
![image](https://user-images.githubusercontent.com/4444428/156939727-96a4cd46-8e39-497d-b0c2-20e4fc97c235.png)


To find out more detailed information I installed docker, run container with INSPIRE validator image, and validated my Atom Feed Download Service on my localhost server. Here are a few lines from log in docker container, maybe it helps to solve problem:




myuser@myserver:/docker/inspire_validator/etf/logs# cat etf.log
.
.
2022-03-06 19:14:38.558 [Thread-132] INFO  d.i.e.t.s.STestCaseRunner - running step [Iterate over Describe Spatial Dataset URL]
2022-03-06 19:14:38.610 [Thread-132] INFO  g.log - describeSpatialDataSetUrls: [<?xml version="1.0" encoding="UTF-8"?>
<Url xmlns="http://a9.com/-/spec/opensearch/1.1/"
     xmlns:inspire_dls="http://inspire.ec.europa.eu/schemas/inspire_dls/1.0"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     type="application/gml+xml"
     rel="results"
     template="https://geos.sazp.sk/inspire/atom/search.php?spatial_dataset_identifier_code={inspire_dls:spatial_dataset_identifier_code?}&amp;spatial_dataset_identifier_namespace={inspire_dls:spatial_dataset_identifier_namespace?}&amp;crs={inspire_dls:crs?}&amp;language={language?}&amp;q={searchTerms?}"/>]
2022-03-06 19:14:38.612 [Thread-132] INFO  g.log - languages: [en]
2022-03-06 19:14:38.612 [Thread-132] INFO  g.log - namespaces: [https://data.gov.sk/set/rpi/dat/00626031/]
2022-03-06 19:14:38.613 [Thread-132] INFO  g.log - codes: [https://data.gov.sk/set/rpi/dat/00626031/CF3D3C625D6E2358E0530110000A920EHULI_INSPIRE_CLC2018_DTS_DID]
2022-03-06 19:14:38.613 [Thread-132] INFO  g.log - Using template URL: https://geos.sazp.sk/inspire/atom/search.php?spatial_dataset_identifier_code={inspire_dls:spatial_dataset_identifier_code?}&spatial_dataset_identifier_namespace={inspire_dls:spatial_dataset_identifier_namespace?}&crs={inspire_dls:crs?}&language={language?}&q={searchTerms?}
2022-03-06 19:14:38.614 [Thread-132] INFO  g.log - Using URL: https://geos.sazp.sk/inspire/atom/search.php?language=en&spatial_dataset_identifier_code=https%3A%2F%2Fdata.gov.sk%2Fset%2Frpi%2Fdat%2F00626031%2FCF3D3C625D6E2358E0530110000A920EHULI_INSPIRE_CLC2018_DTS_DID&spatial_dataset_identifier_namespace=https%3A%2F%2Fdata.gov.sk%2Fset%2Frpi%2Fdat%2F00626031%2F
2022-03-06 19:14:38.614 [Thread-132] INFO  etf-sui-owsgtl - Running test step "Describe Spatial Dataset" requested by test step "Iterate over Describe Spatial Dataset URL"
2022-03-06 19:14:38.616 [Thread-132] INFO  d.i.e.t.s.STestCaseRunner - running step [Describe Spatial Dataset]
2022-03-06 19:14:38.666 [Thread-132] INFO  etf-sui-owsgtl - Running test step "Iterate over Get Spatial Dataset URL" requested by test step "Iterate over Describe Spatial Dataset URL"
2022-03-06 19:14:38.666 [Thread-132] INFO  d.i.e.t.s.STestCaseRunner - running step [Iterate over Get Spatial Dataset URL]
2022-03-06 19:14:38.716 [Thread-132] INFO  g.log - getSpatialDatasetUrls: []
2022-03-06 19:14:38.717 [Thread-132] INFO  g.log - languages: []
2022-03-06 19:14:38.719 [Thread-132] INFO  g.log - namespaces: []
2022-03-06 19:14:38.720 [Thread-132] INFO  g.log - codes: []
2022-03-06 19:14:38.720 [Thread-132] INFO  g.log - CRSs: []
2022-03-06 19:14:38.720 [Thread-132] ERROR d.i.e.t.TestResultCollector - An internal error occurred finishing result 4a9036db-eb9c-458c-b8ad-58b3ff5b82a7
java.lang.ArrayIndexOutOfBoundsException: -1
        at de.interactive_instruments.etf.testdriver.AbstractTestCollector.setStatusAndParentStatus(AbstractTestCollector.java:210)
        at de.interactive_instruments.etf.testdriver.AbstractTestCollector.end(AbstractTestCollector.java:121)
        at de.interactive_instruments.etf.testdriver.AbstractTestResultCollector.doEnd(AbstractTestResultCollector.java:233)
        at de.interactive_instruments.etf.testdriver.AbstractTestCollector.end(AbstractTestCollector.java:119)
        at de.interactive_instruments.etf.sel.mapping.TestRunCollector.afterStep(TestRunCollector.java:464)
        at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.runTestStep(AbstractTestCaseRunner.java:222)
        at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.runTestStepByName(AbstractTestCaseRunner.java:200)
        at com.eviware.soapui.model.testsuite.TestCaseRunner$runTestStepByName.call(Unknown Source)
        at de.interactive_instruments.xtf.ProjectHelper.runTestStep(ProjectHelper.groovy:354)
        at de.interactive_instruments.xtf.ProjectHelper.runTestStep(ProjectHelper.groovy)
        at de.interactive_instruments.xtf.ProjectHelper$runTestStep.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at Script1.run(Script1.groovy:74)
        at com.eviware.soapui.support.scripting.groovy.SoapUIGroovyScriptEngine.run(SoapUIGroovyScriptEngine.java:92)
        at com.eviware.soapui.impl.wsdl.teststeps.WsdlGroovyScriptTestStep.run(WsdlGroovyScriptTestStep.java:141)
        at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.runTestStep(AbstractTestCaseRunner.java:211)
        at com.eviware.soapui.impl.wsdl.testcase.WsdlTestCaseRunner.runCurrentTestStep(WsdlTestCaseRunner.java:47)
        at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.internalRun(AbstractTestCaseRunner.java:138)
        at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.internalRun(AbstractTestCaseRunner.java:46)
        at com.eviware.soapui.impl.wsdl.support.AbstractTestRunner.run(AbstractTestRunner.java:129)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2022-03-06 19:14:38.721 [Thread-132] ERROR c.e.s.SoapUI - An error occurred [java.lang.ArrayIndexOutOfBoundsException: -1], see error log for details
2022-03-06 19:14:38.721 [Thread-132] ERROR s.errorlog - java.lang.IllegalStateException: java.lang.ArrayIndexOutOfBoundsException: -1
java.lang.IllegalStateException: java.lang.ArrayIndexOutOfBoundsException: -1
        at de.interactive_instruments.etf.testdriver.AbstractTestResultCollector.doEnd(AbstractTestResultCollector.java:240)
        at de.interactive_instruments.etf.testdriver.AbstractTestCollector.end(AbstractTestCollector.java:119)
        at de.interactive_instruments.etf.sel.mapping.TestRunCollector.afterStep(TestRunCollector.java:464)
        at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.runTestStep(AbstractTestCaseRunner.java:222)
        at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.runTestStepByName(AbstractTestCaseRunner.java:200)
        at com.eviware.soapui.model.testsuite.TestCaseRunner$runTestStepByName.call(Unknown Source)
        at de.interactive_instruments.xtf.ProjectHelper.runTestStep(ProjectHelper.groovy:354)
        at de.interactive_instruments.xtf.ProjectHelper.runTestStep(ProjectHelper.groovy)
        at de.interactive_instruments.xtf.ProjectHelper$runTestStep.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at Script1.run(Script1.groovy:74)
        at com.eviware.soapui.support.scripting.groovy.SoapUIGroovyScriptEngine.run(SoapUIGroovyScriptEngine.java:92)
        at com.eviware.soapui.impl.wsdl.teststeps.WsdlGroovyScriptTestStep.run(WsdlGroovyScriptTestStep.java:141)
        at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.runTestStep(AbstractTestCaseRunner.java:211)
        at com.eviware.soapui.impl.wsdl.testcase.WsdlTestCaseRunner.runCurrentTestStep(WsdlTestCaseRunner.java:47)
        at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.internalRun(AbstractTestCaseRunner.java:138)
        at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.internalRun(AbstractTestCaseRunner.java:46)
        at com.eviware.soapui.impl.wsdl.support.AbstractTestRunner.run(AbstractTestRunner.java:129)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
        at de.interactive_instruments.etf.testdriver.AbstractTestCollector.setStatusAndParentStatus(AbstractTestCollector.java:210)
        at de.interactive_instruments.etf.testdriver.AbstractTestCollector.end(AbstractTestCollector.java:121)
        at de.interactive_instruments.etf.testdriver.AbstractTestResultCollector.doEnd(AbstractTestResultCollector.java:233)
        ... 24 common frames omitted
2022-03-06 19:14:38.727 [Thread-132] INFO  d.i.e.t.s.STestCaseRunner - Finished running soapUI testcase [Query examples for each dataset], time taken: 838ms, status: FAILED





Thank you
milan

**Comment by JackyDFu** [comment]
@milanSch The problem has not be resolved for us yet, so I welcome further progress in this matter.

**Comment by arantzaetxebarria** [comment]
Dear @JackyDFu, @milanSch 

We have implemented some changes in [issue 751](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/751). Some of them are related to this issue, could you please check these changes in [staging ](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-selection/index.html)environment? Thanks

**Comment by milanSch** [comment]
Dear @arantzaetxebarria, thank you,
I tried to validate atom download service but I am not able get through. There is an error. Please, see
https://github.com/INSPIRE-MIF/helpdesk-validator/issues/722#issuecomment-1130007971
thank you 
milan

**Comment by JackyDFu** [comment]
Dear @arantzaetxebarria, thank you for the response.

I repeated the test steps as described in my [first comment](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/642#issue-1038205726), except I changed the inspire validator url with the staging one. So to reproduce I did the following:

1. Call http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-selection/index.html
2. Select "Download Service"
3. Select pre-defined ATOM
4. Submit service url https://www.srp-gmbh.de/fb/feed/senstadt/a_AD_AdressenBerlin
5. Execute test

Unfortunately after doing so the test seems to fail with an error, similar as @milanSch described.

It seems the test is cancelled, while trying to call a specific url (the testrun itself?):
`http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/validator/v2/TestRuns/EIDc95e0447-b26b-4da0-b565-152e88f94f32.json?_=1653982319689`

but it returns unexpectedly with HTTP 404, as not test can be found under that url:

`TestRunDao: An object with the id "c95e0447-b26b-4da0-b565-152e88f94f32" could not be found!`

I'll add the server response, which I inspected using Chrome Dev Tools for further information:

`
{
  "error": "TestRunDao: An object with the id \"c95e0447-b26b-4da0-b565-152e88f94f32\" could not be found!",
  "timestamp": "1653982458730",
  "url": "http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/validator/v2/TestRuns/EIDc95e0447-b26b-4da0-b565-152e88f94f32.json",
  "stacktrace": [
    "de.interactive_instruments.exceptions.ObjectWithIdNotFoundException: TestRunDao: An object with the id \"c95e0447-b26b-4da0-b565-152e88f94f32\" could not be found!",
    "\tat de.interactive_instruments.etf.dal.dao.basex.AbstractBsxDao.getById(AbstractBsxDao.java:209)",
    "\tat de.interactive_instruments.etf.dal.dao.PreparedDtoResolver.getById(PreparedDtoResolver.java:49)",
    "\tat de.interactive_instruments.etf.webapp.controller.StreamingService.asJson2(StreamingService.java:161)",
    "\tat de.interactive_instruments.etf.webapp.controller.TestResultController.testRunByIdJson(TestResultController.java:381)",
    "\tat sun.reflect.GeneratedMethodAccessor228.invoke(Unknown Source)",
    "\tat sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
    "\tat java.lang.reflect.Method.invoke(Method.java:497)",
    "\tat org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)",
    "\tat org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)",
    "\tat org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)",
    "\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)",
    "\tat org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)",
    "\tat org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)",
    "\tat org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)",
    "\tat org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)",
    "\tat org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)",
    "\tat org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)",
    "\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:687)",
    "\tat org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)",
    "\tat javax.servlet.http.HttpServlet.service(HttpServlet.java:790)",
    "\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)",
    "\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)",
    "\tat de.interactive_instruments.etf.webapp.filter.ApiFilter.doFilterInternal(ApiFilter.java:89)",
    "\tat org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)",
    "\tat org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)",
    "\tat org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)",
    "\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)",
    "\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)",
    "\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)",
    "\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)",
    "\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)",
    "\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)",
    "\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)",
    "\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)",
    "\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)",
    "\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)",
    "\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)",
    "\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)",
    "\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)",
    "\tat org.eclipse.jetty.server.Server.handle(Server.java:517)",
    "\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)",
    "\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)",
    "\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)",
    "\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)",
    "\tat org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)",
    "\tat org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)",
    "\tat org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)",
    "\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)",
    "\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)",
    "\tat java.lang.Thread.run(Thread.java:745)"
  ]
}`

It would be great if this issue could be examined again, as in the current state I am not able to check if the issue is resolved yet.

Thank you for your help and kind regards,
Jacky

**Comment by milanSch** [comment]
Hello @arantzaetxebarria, @dperezBM, @JackyDFu, 

I validated my atom download service https://geos.sazp.sk/inspire/atom/DownloadServiceFeed.xml again. Just to see how it is going. 

Test using https://inspire.ec.europa.eu/validator/test-selection/index.html has the same error as in the top of this issue or in https://github.com/INSPIRE-MIF/helpdesk-validator/issues/722#issue-1164237306 issue.

![image](https://user-images.githubusercontent.com/4444428/190429709-f95f1f26-0049-4638-ba0a-e197720ed2f9.png)


Next I used http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-selection/index.html but this one hanged up 

http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-run/index.html?id=EID51daa5b7-c3f0-4efb-b830-f39cc17c54ff

![image](https://user-images.githubusercontent.com/4444428/190431192-b664fb01-3702-4cc5-8fc0-d6ff6cf0dc21.png)


There were errors in 'Log file' http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/validator/v2/TestRuns/EID51daa5b7-c3f0-4efb-b830-f39cc17c54ff/log

![image](https://user-images.githubusercontent.com/4444428/190430883-79386ce7-8a8b-4d3e-b414-a95d83cb4dd9.png)
and much more ...

So it seems that problem persists. (I have found some new hint here https://github.com/INSPIRE-MIF/helpdesk-validator/issues/751#issuecomment-1208068302 too.)

thank you
milan

**Comment by arantzaetxebarria** [comment]
Dear @JackyDFu 

We have implemented some changes related to the issue https://github.com/INSPIRE-MIF/helpdesk-validator/issues/819, these changes seem to fix this issue, could you please verify? Many thanks

Best regards

**Comment by fabiovinci** [comment]
Dear @JackyDFu,
were you able to test your service with the latest release?

**Comment by fabiovinci** [comment]
Dear @JackyDFu,

the error you reported is no longer present (see attached validation report), so we will consider the issue as solved.

[PROD_Test run on 13_05 - 13.09.2023 with test suite Conformance Class Pre-defined Atom - IOS 642.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/12597262/PROD_Test.run.on.13_05.-.13.09.2023.with.test.suite.Conformance.Class.Pre-defined.Atom.-.IOS.642.zip)
