### ISSUE TITLE
(Predefined-ATOM) Query examples for each dataset / Iterate Over Get Spatial Dataset URL

### ISSUE THREAD

**Issue by milanSch** [INSPIRE-MIF/helpdesk-validator#722]
Hello,
it seems to be a problem during test validation of 'Download Service - Pre-defined Atom'.

I validate this download service: https://geos.sazp.sk/inspire/atom/DownloadServiceFeed.xml

Test result: https://yzyiqfakm4.execute-api.eu-west-1.amazonaws.com/validator/v2/TestRuns/EID2b1eca9b-1662-434a-ad48-2935e25fa77f.html?lang=en#EID6f60d4f2-017f-1000-abd2-7708af45ceb9

In test result path: Conformance Class: Download Service - Pre-defined Atom / OpenSearch Description / Query examples for each dataset / Iterate over Describe Spatial Dataset Url

there is a 'Test Instruction code':
```
.
.
.
for( node in describeSpatialDataSetUrlTemplates ) {
	String describeSpatialDataSetUrlTemplate = node.attributes.getNamedItem("template").getNodeValue()
	String mimeType = node.attributes.getNamedItem("type").getNodeValue()

	log.info("Using template URL: "+describeSpatialDataSetUrlTemplate);
	def parameters = UriUtils.getQueryParameters(describeSpatialDataSetUrlTemplate, false)
	final Map<String, String> cleanParameters = initDefaultParameters(parameters)
	final String endpoint = UriUtils.withoutQueryParameters(describeSpatialDataSetUrlTemplate)

	for(int j=0; j<codes.size(); j++) {
		replaceParameter(parameters, cleanParameters, "inspire_dls:spatial_dataset_identifier_code", codes[j] )
		replaceParameter(parameters, cleanParameters, "inspire_dls:spatial_dataset_identifier_namespace", namespaces[j] )

			for(language in languages) {
				replaceParameter(parameters, cleanParameters, "language", language )
				final String url = UriUtils.withQueryParameters(endpoint, cleanParameters)
				if(!invokedUrls.contains(url)) {
					log.info("Using URL: "+url)
					ph.setTransferProperty("describeSpatialDataSetUrl", url)
					ph.setTransferProperty("mimeType", mimeType)
					ph.runTestStep("Describe Spatial Dataset");
					ph.runTestStep("Iterate over Get Spatial Dataset URL");
					invokedUrls.add(url);
				}
			}
	}
}
```
the line 

`ph.runTestStep("Iterate over Get Spatial Dataset URL");`

calls next TestStep "Iterate over Get Spatial Dataset URL" with 'Test Instruction code':

```
import de.interactive_instruments.xtf.*;
SOAPUI_I.init(log,context,testRunner);
import de.interactive_instruments.UriUtils;

ProjectHelper ph = new ProjectHelper();
def xmlHolder = ph.getTestStepResult("Describe Spatial Dataset")

def getSpatialDataSetUrlTemplates = xmlHolder.getDomNodes(
	"/*:OpenSearchDescription/*:Url[@rel='results' and starts-with(@template,'http') and "+
	"contains(@template,'crs') and contains(@template,'spatial_dataset_identifier_code') and "+
	"contains(@template,'spatial_dataset_identifier_namespace') and contains(@template,'language')]");
log.info("getSpatialDatasetUrls: " + getSpatialDataSetUrlTemplates);
.
.
.
```

The line 

`def xmlHolder = ph.getTestStepResult("Describe Spatial Dataset")`

should be probably changed to 

`def xmlHolder = ph.getTestStepResult("Get OpenSearch Description")`

The result of test "Describe Spatial Dataset" doesn't contain any 'Spatial Data Set Operation request URL template' needed in lines
```
def getSpatialDataSetUrlTemplates = xmlHolder.getDomNodes(
	"/*:OpenSearchDescription/*:Url[@rel='results' and starts-with(@template,'http') and "+
	"contains(@template,'crs') and contains(@template,'spatial_dataset_identifier_code') and "+
	"contains(@template,'spatial_dataset_identifier_namespace') and contains(@template,'language')]");
log.info("getSpatialDatasetUrls: " + getSpatialDataSetUrlTemplates);
```
but it contains Dataset Atom Feed file.

Log is 
(in my Docker inspire validator container v2022.0 19/01/2022 : etf/logs/etf.log
https://github.com/INSPIRE-MIF/helpdesk-validator/releases/
):
_2022-03-09 16:31:09.806 [Thread-166] INFO  d.i.e.t.s.STestCaseRunner - running step [Iterate over Describe Spatial Dataset URL]
2022-03-09 16:31:09.860 [Thread-166] INFO  g.log - describeSpatialDataSetUrls: [<?xml version="1.0" encoding="UTF-8"?>
<Url xmlns="http://a9.com/-/spec/opensearch/1.1/"
     xmlns:inspire_dls="http://inspire.ec.europa.eu/schemas/inspire_dls/1.0"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     type="application/gml+xml"
     rel="results"
     template="https://geos.sazp.sk/inspire/atom/search.php?spatial_dataset_identifier_code={inspire_dls:spatial_dataset_identifier_code?}&amp;spatial_dataset_identifier_namespace={inspire_dls:spatial_dataset_identifier_namespace?}&amp;crs={inspire_dls:crs?}&amp;language={language?}&amp;q={searchTerms?}"/>]
2022-03-09 16:31:09.861 [Thread-166] INFO  g.log - languages: [en]
2022-03-09 16:31:09.861 [Thread-166] INFO  g.log - namespaces: [https://data.gov.sk/set/rpi/dat/00626031/]
2022-03-09 16:31:09.862 [Thread-166] INFO  g.log - codes: [https://data.gov.sk/set/rpi/dat/00626031/CF3D3C625D6E2358E0530110000A920EHULI_INSPIRE_CLC2018_DTS_DID]
2022-03-09 16:31:09.862 [Thread-166] INFO  g.log - Using template URL: https://geos.sazp.sk/inspire/atom/search.php?spatial_dataset_identifier_code={inspire_dls:spatial_dataset_identifier_code?}&spatial_dataset_identifier_namespace={inspire_dls:spatial_dataset_identifier_namespace?}&crs={inspire_dls:crs?}&language={language?}&q={searchTerms?}
2022-03-09 16:31:09.864 [Thread-166] INFO  g.log - Using URL: https://geos.sazp.sk/inspire/atom/search.php?language=en&spatial_dataset_identifier_code=https%3A%2F%2Fdata.gov.sk%2Fset%2Frpi%2Fdat%2F00626031%2FCF3D3C625D6E2358E0530110000A920EHULI_INSPIRE_CLC2018_DTS_DID&spatial_dataset_identifier_namespace=https%3A%2F%2Fdata.gov.sk%2Fset%2Frpi%2Fdat%2F00626031%2F
2022-03-09 16:31:09.864 [Thread-166] INFO  etf-sui-owsgtl - Running test step "Describe Spatial Dataset" requested by test step "Iterate over Describe Spatial Dataset URL"
2022-03-09 16:31:09.865 [Thread-166] INFO  d.i.e.t.s.STestCaseRunner - running step [Describe Spatial Dataset]
2022-03-09 16:31:09.901 [Thread-166] INFO  etf-sui-owsgtl - Running test step "Iterate over Get Spatial Dataset URL" requested by test step "Iterate over Describe Spatial Dataset URL"
2022-03-09 16:31:09.901 [Thread-166] INFO  d.i.e.t.s.STestCaseRunner - running step [Iterate over Get Spatial Dataset URL]
2022-03-09 16:31:09.931 [Thread-166] INFO  g.log - getSpatialDatasetUrls: []
2022-03-09 16:31:09.931 [Thread-166] INFO  g.log - languages: []
2022-03-09 16:31:09.931 [Thread-166] INFO  g.log - namespaces: []
2022-03-09 16:31:09.932 [Thread-166] INFO  g.log - codes: []
2022-03-09 16:31:09.932 [Thread-166] INFO  g.log - CRSs: []
2022-03-09 16:31:09.933 [Thread-166] ERROR d.i.e.t.TestResultCollector - An internal error occurred finishing result 4a9036db-eb9c-458c-b8ad-58b3ff5b82a7
java.lang.ArrayIndexOutOfBoundsException: -1_

It is possible to see empty variables there:

_2022-03-09 16:31:09.931 [Thread-166] INFO  g.log - getSpatialDatasetUrls: []
2022-03-09 16:31:09.931 [Thread-166] INFO  g.log - languages: []
2022-03-09 16:31:09.931 [Thread-166] INFO  g.log - namespaces: []
2022-03-09 16:31:09.932 [Thread-166] INFO  g.log - codes: []
2022-03-09 16:31:09.932 [Thread-166] INFO  g.log - CRSs: []_

After correction from 
`def xmlHolder = ph.getTestStepResult("Describe Spatial Dataset")`
to
`def xmlHolder = ph.getTestStepResult("Get OpenSearch Description")`

Log is:
_2022-03-09 16:37:12.927 [Thread-243] INFO  d.i.e.t.s.STestCaseRunner - running step [Iterate over Describe Spatial Dataset URL]
2022-03-09 16:37:13.132 [Thread-243] INFO  g.log - describeSpatialDataSetUrls: [<?xml version="1.0" encoding="UTF-8"?>
<Url xmlns="http://a9.com/-/spec/opensearch/1.1/"
     xmlns:inspire_dls="http://inspire.ec.europa.eu/schemas/inspire_dls/1.0"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     type="application/gml+xml"
     rel="results"
     template="https://geos.sazp.sk/inspire/atom/search.php?spatial_dataset_identifier_code={inspire_dls:spatial_dataset_identifier_code?}&amp;spatial_dataset_identifier_namespace={inspire_dls:spatial_dataset_identifier_namespace?}&amp;crs={inspire_dls:crs?}&amp;language={language?}&amp;q={searchTerms?}"/>]
2022-03-09 16:37:13.132 [Thread-243] INFO  g.log - languages: [en]
2022-03-09 16:37:13.133 [Thread-243] INFO  g.log - namespaces: [https://data.gov.sk/set/rpi/dat/00626031/]
2022-03-09 16:37:13.133 [Thread-243] INFO  g.log - codes: [https://data.gov.sk/set/rpi/dat/00626031/CF3D3C625D6E2358E0530110000A920EHULI_INSPIRE_CLC2018_DTS_DID]
2022-03-09 16:37:13.133 [Thread-243] INFO  g.log - Using template URL: https://geos.sazp.sk/inspire/atom/search.php?spatial_dataset_identifier_code={inspire_dls:spatial_dataset_identifier_code?}&spatial_dataset_identifier_namespace={inspire_dls:spatial_dataset_identifier_namespace?}&crs={inspire_dls:crs?}&language={language?}&q={searchTerms?}
2022-03-09 16:37:13.135 [Thread-243] INFO  g.log - Using URL: https://geos.sazp.sk/inspire/atom/search.php?language=en&spatial_dataset_identifier_code=https%3A%2F%2Fdata.gov.sk%2Fset%2Frpi%2Fdat%2F00626031%2FCF3D3C625D6E2358E0530110000A920EHULI_INSPIRE_CLC2018_DTS_DID&spatial_dataset_identifier_namespace=https%3A%2F%2Fdata.gov.sk%2Fset%2Frpi%2Fdat%2F00626031%2F
2022-03-09 16:37:13.135 [Thread-243] INFO  etf-sui-owsgtl - Running test step "Describe Spatial Dataset" requested by test step "Iterate over Describe Spatial Dataset URL"
2022-03-09 16:37:13.135 [Thread-243] INFO  d.i.e.t.s.STestCaseRunner - running step [Describe Spatial Dataset]
2022-03-09 16:37:13.281 [Thread-243] INFO  etf-sui-owsgtl - Running test step "Iterate over Get Spatial Dataset URL" requested by test step "Iterate over Describe Spatial Dataset URL"
2022-03-09 16:37:13.281 [Thread-243] INFO  d.i.e.t.s.STestCaseRunner - running step [Iterate over Get Spatial Dataset URL]
2022-03-09 16:37:13.383 [Thread-243] INFO  g.log - getSpatialDatasetUrls: [<?xml version="1.0" encoding="UTF-8"?>
<Url xmlns="http://a9.com/-/spec/opensearch/1.1/"
     xmlns:inspire_dls="http://inspire.ec.europa.eu/schemas/inspire_dls/1.0"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     type="application/gml+xml"
     rel="results"
     template="https://geos.sazp.sk/inspire/atom/search.php?spatial_dataset_identifier_code={inspire_dls:spatial_dataset_identifier_code?}&amp;spatial_dataset_identifier_namespace={inspire_dls:spatial_dataset_identifier_namespace?}&amp;crs={inspire_dls:crs?}&amp;language={language?}&amp;q={searchTerms?}"/>]
2022-03-09 16:37:13.383 [Thread-243] INFO  g.log - languages: [en]
2022-03-09 16:37:13.384 [Thread-243] INFO  g.log - namespaces: [https://data.gov.sk/set/rpi/dat/00626031/]
2022-03-09 16:37:13.392 [Thread-243] INFO  g.log - codes: [https://data.gov.sk/set/rpi/dat/00626031/CF3D3C625D6E2358E0530110000A920EHULI_INSPIRE_CLC2018_DTS_DID]
2022-03-09 16:37:13.393 [Thread-243] INFO  g.log - CRSs: [http://www.opengis.net/def/crs/EPSG/0/4258]
2022-03-09 16:37:13.393 [Thread-243] INFO  g.log - Using template URL: https://geos.sazp.sk/inspire/atom/search.php?spatial_dataset_identifier_code={inspire_dls:spatial_dataset_identifier_code?}&spatial_dataset_identifier_namespace={inspire_dls:spatial_dataset_identifier_namespace?}&crs={inspire_dls:crs?}&language={language?}&q={searchTerms?}
2022-03-09 16:37:13.401 [Thread-243] INFO  g.log - Using URL: https://geos.sazp.sk/inspire/atom/search.php?crs=http%3A%2F%2Fwww.opengis.net%2Fdef%2Fcrs%2FEPSG%2F0%2F4258&language=en&spatial_dataset_identifier_code=https%3A%2F%2Fdata.gov.sk%2Fset%2Frpi%2Fdat%2F00626031%2FCF3D3C625D6E2358E0530110000A920EHULI_INSPIRE_CLC2018_DTS_DID&spatial_dataset_identifier_namespace=https%3A%2F%2Fdata.gov.sk%2Fset%2Frpi%2Fdat%2F00626031%2F
2022-03-09 16:37:13.401 [Thread-243] INFO  etf-sui-owsgtl - Running test step "Get Spatial Dataset" requested by test step "Iterate over Describe Spatial Dataset URL"
2022-03-09 16:37:13.402 [Thread-243] INFO  d.i.e.t.s.STestCaseRunner - running step [Get Spatial Dataset]
2022-03-09 16:37:13.469 [Thread-243] ERROR d.i.e.t.TestResultCollector - An internal error occurred finishing result 3e55838a-6ac8-422c-84f3-a958d9956095
java.lang.ArrayIndexOutOfBoundsException: -1_

and variables are assigned:

_2022-03-09 16:37:13.383 [Thread-243] INFO  g.log - languages: [en]
2022-03-09 16:37:13.384 [Thread-243] INFO  g.log - namespaces: [https://data.gov.sk/set/rpi/dat/00626031/]
2022-03-09 16:37:13.392 [Thread-243] INFO  g.log - codes: [https://data.gov.sk/set/rpi/dat/00626031/CF3D3C625D6E2358E0530110000A920EHULI_INSPIRE_CLC2018_DTS_DID]
2022-03-09 16:37:13.393 [Thread-243] INFO  g.log - CRSs: [http://www.opengis.net/def/crs/EPSG/0/4258]_

In both cases (before and after correction of  code) test validation ended up with errors:

_2022-03-09 16:37:13.469 [Thread-243] ERROR d.i.e.t.TestResultCollector - An internal error occurred finishing result 3e55838a-6ac8-422c-84f3-a958d9956095
java.lang.ArrayIndexOutOfBoundsException: -1
        at de.interactive_instruments.etf.testdriver.AbstractTestCollector.setStatusAndParentStatus(AbstractTestCollector.java:210)
        at de.interactive_instruments.etf.testdriver.AbstractTestCollector.releaseSubCollector(AbstractTestCollector.java:198)
        at de.interactive_instruments.etf.testdriver.AbstractTestStepResultCollector.doEnd(AbstractTestStepResultCollector.java:153)
        at de.interactive_instruments.etf.testdriver.AbstractTestCollector.end(AbstractTestCollector.java:119)
        at de.interactive_instruments.etf.testdriver.AbstractTestStepResultCollector.doEnd(AbstractTestStepResultCollector.java:164)
        at de.interactive_instruments.etf.testdriver.AbstractTestCollector.end(AbstractTestCollector.java:119)
        at de.interactive_instruments.etf.testdriver.AbstractTestResultCollector.doEnd(AbstractTestResultCollector.java:233)
        at de.interactive_instruments.etf.testdriver.AbstractTestCollector.end(AbstractTestCollector.java:132)
        at de.interactive_instruments.etf.sel.mapping.TestRunCollector.afterStep(TestRunCollector.java:462)
        at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.runTestStep(AbstractTestCaseRunner.java:222)
        at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.runTestStepByName(AbstractTestCaseRunner.java:200)
        at com.eviware.soapui.model.testsuite.TestCaseRunner$runTestStepByName.call(Unknown Source)
        at de.interactive_instruments.xtf.ProjectHelper.runTestStep(ProjectHelper.groovy:354)
        at de.interactive_instruments.xtf.ProjectHelper.runTestStep(ProjectHelper.groovy)
        at de.interactive_instruments.xtf.ProjectHelper$runTestStep.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at Script1.run(Script1.groovy:80)
        at com.eviware.soapui.support.scripting.groovy.SoapUIGroovyScriptEngine.run(SoapUIGroovyScriptEngine.java:92)
        at com.eviware.soapui.impl.wsdl.teststeps.WsdlGroovyScriptTestStep.run(WsdlGroovyScriptTestStep.java:141)
        at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.runTestStep(AbstractTestCaseRunner.java:211)
        at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.runTestStepByName(AbstractTestCaseRunner.java:200)
        at com.eviware.soapui.model.testsuite.TestCaseRunner$runTestStepByName.call(Unknown Source)
        at de.interactive_instruments.xtf.ProjectHelper.runTestStep(ProjectHelper.groovy:354)
        at de.interactive_instruments.xtf.ProjectHelper.runTestStep(ProjectHelper.groovy)
        at de.interactive_instruments.xtf.ProjectHelper$runTestStep.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
        at Script1.run(Script1.groovy:74)
        at com.eviware.soapui.support.scripting.groovy.SoapUIGroovyScriptEngine.run(SoapUIGroovyScriptEngine.java:92)
        at com.eviware.soapui.impl.wsdl.teststeps.WsdlGroovyScriptTestStep.run(WsdlGroovyScriptTestStep.java:141)
        at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.runTestStep(AbstractTestCaseRunner.java:211)
        at com.eviware.soapui.impl.wsdl.testcase.WsdlTestCaseRunner.runCurrentTestStep(WsdlTestCaseRunner.java:47)
        at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.internalRun(AbstractTestCaseRunner.java:138)
        at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.internalRun(AbstractTestCaseRunner.java:46)
        at com.eviware.soapui.impl.wsdl.support.AbstractTestRunner.run(AbstractTestRunner.java:129)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2022-03-09 16:37:13.539 [Thread-243] ERROR d.i.e.t.TestResultCollector - An internal error occurred finishing result 3e55838a-6ac8-422c-84f3-a958d9956095
java.lang.IllegalStateException: java.lang.ArrayIndexOutOfBoundsException: -1
        at de.interactive_instruments.etf.testdriver.AbstractTestStepResultCollector.doEnd(AbstractTestStepResultCollector.java:171)
.
.
._

This 'java.lang.IllegalStateException: java.lang.ArrayIndexOutOfBoundsException: -1' is probably next different problem (I can't find a reason).

My issue is related to and continues after this one https://github.com/INSPIRE-MIF/helpdesk-validator/issues/642#issue-1038205726 

Maybe I am completely wrong but definitely thank you for your time.

milan

**Comment by milanSch** [comment]
Dear, 
just wanted to ask, is something new with this issue? 

thank you 
milan

**Comment by arantzaetxebarria** [comment]
Dear @milanSch 

We have implemented some changes in [issue 751](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/751). Some of them are related to this issue, could you please check these changes in [staging ](http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-selection/index.html)environment? Thanks

**Comment by milanSch** [comment]
Dear @arantzaetxebarria, thank you.

I tried to validate atom download service: 
https://geos.sazp.sk/inspire/atom/DownloadServiceFeed.xml
by staging validator 
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/etf-webapp/test-selection/index.html
but I am not able get through. There is an error:

```
<etf:error>
TestRunDao: An object with the id "1a80a752-3f2c-4d15-837e-a7b6bca093cc" could not be found!
</etf:error>
```
http://staging-inspire-validator.eu-west-1.elasticbeanstalk.com/validator/v2/TestRuns/EID1a80a752-3f2c-4d15-837e-a7b6bca093cc.xml

![image](https://user-images.githubusercontent.com/4444428/169043867-320047f3-38f0-4e34-b92b-2fd9620e470c.png)

When I used 
https://inspire.ec.europa.eu/validator/test-selection/index.html
it worked as usual and I obtained validation report.
![image](https://user-images.githubusercontent.com/4444428/169047665-35f62e14-0c16-4dda-9792-abd7056c366c.png)




thank you
milan

**Comment by milanSch** [comment]
Hello, 
I put a comment here https://github.com/INSPIRE-MIF/helpdesk-validator/issues/642#issuecomment-1248219902

thank you 
milan

**Comment by arantzaetxebarria** [comment]
Dear @milanSch 

We have implemented some changes related to the issue https://github.com/INSPIRE-MIF/helpdesk-validator/issues/819, these changes seem to fix this issue, could you please verify? Many thanks

Best regards

**Comment by milanSch** [comment]
Dear @arantzaetxebarria,
thank you for information. Unfortunately my testing data has changed and I cannot repeat testing (verification).  So, please close this issue.

Thank you
milan

**Comment by fabiovinci** [comment]
Dear @milanSch,

thank you for your feedback.
In any case, by validating the service the initially reported error is no longer present.
We will close the issue, please reopen the issue or open a new one if the error persists.
