### ISSUE TITLE
Can't run tests locally

### ISSUE THREAD

**Issue by tfunq** [INSPIRE-MIF/helpdesk-validator#827]
I have the same problem as reported in #675, using latest version 2022.2.

I'm running the docker image locally using

```
docker run --name inspire-validator -p 8090:8090 docker.pkg.github.com/inspire-mif/helpdesk-validator/inspire-validator:2022.2
```

The container starts fine, and I'm able to access the GUI on [http://localhost:8090/validator](http://localhost:8090/validator).

Executing a test gives following error in `/etf/log/etf.log`:

```
2022-08-17 14:28:12.867 [qtp633075331-14] ERROR d.i.e.w.d.ApiError - EXID-1660746492865: An exception occurred while trying to invoke "http://localhost/validator/v2/TestRuns"
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is de.interactive_instruments.etf.webapp.controller.LocalizableApiError
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:982)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
	at de.interactive_instruments.etf.webapp.filter.ApiFilter.doFilterInternal(ApiFilter.java:89)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: de.interactive_instruments.etf.webapp.controller.LocalizableApiError: null
	at de.interactive_instruments.etf.webapp.controller.StatusController.ensureStatusNotMajor(StatusController.java:296)
	at de.interactive_instruments.etf.webapp.controller.TestRunController.start(TestRunController.java:464)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

`etf.webapp.base.url` in `/etf/config/etf-config.properties` is set to `http://localhost:8090/validator`
`serverURL` in `/etf/validator/js/config.js` is set to `http://localhost:8090/validator/v2/`.

**Comment by milanSch** [comment]
Hi @tfunq,
if it is the same problem as https://github.com/INSPIRE-MIF/helpdesk-validator/issues/675 try this https://github.com/INSPIRE-MIF/helpdesk-validator/issues/675#issuecomment-1249240157

milan

**Comment by fabiovinci** [comment]
Dear @milanSch,

thank you for your suggestion.

@tfunq, could you please try if the solution provided by @milanSch works for you? Thanks

**Comment by tfunq** [comment]
Dear @milanSch and @fabiovinci ,
I tried the solution but got the same error:
```
2022-09-21 05:29:38.334 [qtp633075331-21] ERROR d.i.e.w.d.ApiError - EXID-1663738178331: An exception occurred while trying to invoke "http://localhost/validator/v2/TestRuns"
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is de.interactive_instruments.etf.webapp.controller.LocalizableApiError
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:982)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
```
It is trying to invoke http://localhost/validator/v2/TestRuns although `/etf/config/etf-config.properties` says
```
etf.webapp.base.url = https://localhost:8090/validator
```
and `/etf/validator/js/config.js` says
```
var serverURL = "http://localhost:8090/validator/v2/";
var serverRealURL = "http://localhost:8090/validator/v2/";
var serverDirectURL = "http://localhost:8090/validator/v2/";
```

**Comment by milanSch** [comment]
Dear @tfunq,
what exactly  are you testing? 
Could you give us a url link or data file to test?
Doesn't your validator work at all or just during testing a specific metadata?


I have look in my log file and there is similar error:
.../etf/logs# cat etf.log

`2022-09-16 08:10:09.351 [qtp633075331-13] ERROR d.i.e.w.d.ApiError - EXID-1663315809348: An exception occurred while trying to invoke "http://localhost/validator/v2/TestRuns"
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is de.interactive_instruments.etf.webapp.controller.LocalizableApiError: de.interactive_instruments.etf.detector.TestObjectTypeNotDetected: Could not detect any matching Test Object Type
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:982)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:821)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
        at de.interactive_instruments.etf.webapp.filter.ApiFilter.doFilterInternal(ApiFilter.java:89)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
        at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
        at org.eclipse.jetty.server.Server.handle(Server.java:517)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
        at java.lang.Thread.run(Thread.java:745)
Caused by: de.interactive_instruments.etf.webapp.controller.LocalizableApiError: de.interactive_instruments.etf.detector.TestObjectTypeNotDetected: Could not detect any matching Test Object Type
        at de.interactive_instruments.etf.webapp.controller.TestObjectTypeController.checkAndResolveTypes(TestObjectTypeController.java:106)
        at de.interactive_instruments.etf.webapp.controller.TestObjectController.initResourcesAndAdd(TestObjectController.java:438)
        at de.interactive_instruments.etf.webapp.controller.TestRunController.start(TestRunController.java:497)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        ... 36 common frames omitted
Caused by: de.interactive_instruments.etf.detector.TestObjectTypeNotDetected: Could not detect any matching Test Object Type
        at de.interactive_instruments.etf.detector.TestObjectTypeDetectorManager.detect(TestObjectTypeDetectorManager.java:316)
        at de.interactive_instruments.etf.webapp.controller.TestObjectTypeController.checkAndResolveTypes(TestObjectTypeController.java:104)
        ... 49 common frames omitted
`



It happened when I tried to validate metadata but input url had a "incorrect" parameter. When I corrected the parameter url test passed.



milan

**Comment by tfunq** [comment]
Hi,
An example that failes is download service, atom, https://opendata-download-icemap.smhi.se/inspire.xml. It works in the inspire validator at https://inspire.ec.europa.eu/validator.

**Comment by milanSch** [comment]
Hello, 
I have tested your DownloadServiceFeed using 
- https://inspire.ec.europa.eu/validator 
https://inspire.ec.europa.eu/validator/test-run/details.html?id=EID3651bb95-0e76-451d-93ef-864638fdab56

- http://localhost:8090/validator/test-selection/index.html (ver. 2022.2).  
[Test run on 10 22 - 21.09.2022 with test suite Conformance Class Pre-defined Atom.zip](https://github.com/INSPIRE-MIF/helpdesk-validator/files/9614836/Test.run.on.10.22.-.21.09.2022.with.test.suite.Conformance.Class.Pre-defined.Atom.zip)

Both of them passed (surprisingly with different errors...). 

I do not know why your local validator doesn't work. If I were you, I would completely reinstall docker container (remove container, images and proceed with a new install).

My working configuration/installation:
--Debian 11.1.0 - Bullseye
--INSPIRE Validator Version v2022.2- 21/06/2022

```
root@myserver:~# mkdir -p /docker/inspire_validator_v2022.2

root@myserver:~# cd /docker/inspire_validator_v2022.2

root@myserver:/docker/inspire_validator_v2022.1# docker login docker.pkg.github.com

root@myserver:/docker/inspire_validator_v2022.2# docker run --name inspire-validator_v2022.2 -d -p 8090:8090 -v /docker/inspire_validator_v2022.2/etf:/etf docker.pkg.github.com/inspire-mif/helpdesk-validator/inspire-validator:2022.2

root@myserver:/docker/inspire_validator_v2022.2#cd etf/config

root@myserver:/docker/inspire_validator_v2022.2/etf/config# vi etf-config.properties
#change to true
etf.testobject.allow.privatenet.access = true
root@myserver:/docker/inspire_validator_v2022.2/etf/config#


root@myserver:/docker/inspire_validator_v2022.2# docker ps
CONTAINER ID   IMAGE                                                                           COMMAND                  CREATED      STATUS          PORTS                                                 NAMES
0f9c983db81e   docker.pkg.github.com/inspire-mif/helpdesk-validator/inspire-validator:2022.2   "/docker-entrypoint.…"   5 days ago   Up 31 seconds   8080/tcp, 0.0.0.0:8090->8090/tcp, :::8090->8090/tcp   inspire-validator_v2022.2

root@myserver:/docker/inspire_validator_v2022.2# docker stop inspire-validator_v2022.2
inspire-validator_v2022.2

root@myserver:/docker/inspire_validator_v2022.2# docker start inspire-validator_v2022.2
inspire-validator_v2022.2
root@myserver:/docker/inspire_validator_v2022.2#
```

Log in to myserver as regular user (I am using GMOME) .
In Firefox open url http://localhost:8090/validator/home/index.html or http://localhost:8090/validator/test-selection/index.html .
This  works for me. 

milan

**Comment by jenriquesoriano** [comment]
Dear @tfunq , @milanSch 

thanks for your feedback and contributions.
We have downloaded the official version you used (v2022.2) and we tried to test some tests but they run successfully. 
So we couldn't reproduce your error.

Could you provide us with more information about what kind of test are you trying to test to be able to reproduce it?

Anyway, we reccomend you to update to v2022.3 to stay up to date with the latest version of the ETSs.

Best,

**Comment by tfunq** [comment]
After some local investigating it turned out that we had to open up our firewall for some sites. Namely https://files.basex.org,  https://cite.opengeospatial.org, https://services.interactive-instruments.de, https://af4.etf.interactive-instruments.de, https://github.com and https://codeload.github.com.

So no problems with the validator (except needing thoose sites). In other words, you can cloose this issue.
